# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: ["m7i-flexi.large", "c7i-flexi.large"]
  spot: true
  desiredCapacity: 2